### ISSUE TITLE
BUG: Appearance >> Customize >> Typography changes not updated in preview pane

### ISSUE THREAD

**Issue by chadmeby** [pacethemes/quest#1]
When making changes to typography options via the customizer, user changes are not reflected in the update pane. The pane "dims" and reloads, but the content does not change.

Pressing the "Save & Publish" button followed by a manual browser refresh does show the changes in the preview pane.

This is also true of Appearance >> Customize >> Colors >> \* (Header >> Header Text Color, for example), however, Appearance >> Customize >> Widgets >> Footer Widget DOES update the preview when selected.

I see this behavior in Firefox Version 38.0.5 and Chrome Version 43.0.2357.130 (64-bit) on OS X.

**Comment by pacethemes** [comment]
Customizer Preview JavaScript support will be added in Quest version 1.1.0 and it should address these issues, the tentative date for this release is 30th July 2015.
